"""remove_api_key_from_users_table

Revision ID: 6ee1a8575943
Revises: add_api_key_to_users
Create Date: 2025-10-01 16:22:44.076398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ee1a8575943'
down_revision = 'add_api_key_to_users'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_tools', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_agent_tools_id'), table_name='agent_tools')
    op.create_foreign_key(None, 'agent_tools', 'tools', ['tool_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_tools', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('agent_tools', 'id')
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'auth_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'embeddings', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_executions_session_id'), 'executions', ['session_id'], unique=False)
    op.create_foreign_key(None, 'executions', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_users_api_key'), 'users', type_='unique')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_users_api_key'), 'users', ['api_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_index(op.f('ix_executions_session_id'), table_name='executions')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.drop_constraint(None, 'auth_tokens', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.add_column('agent_tools', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agent_tools', type_='foreignkey')
    op.drop_constraint(None, 'agent_tools', type_='foreignkey')
    op.create_index(op.f('ix_agent_tools_id'), 'agent_tools', ['id'], unique=False)
    op.alter_column('agent_tools', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###